app:
  name: 'L0'
  version: '1.0.0'

postgres:
  host: '127.0.0.1'
  port: '5432'
  user: 'postgres'
  password: 'postgres'
  name: 'main'
  pg_driver: 'pq'

http:
  host: 'localhost'
  port: '8080'

nats:
  host: 'localhost'
  port: '4222'
  cluster: 'test-cluster'
  client: "event-listener"
  topic: "main-chanel"